feat: running CI/CD with on user github-runner

diff --git a/.github/workflows/node.yml b/.github/workflows/node.yml
--- a/.github/workflows/node.yml
+++ b/.github/workflows/node.yml
@@ -6,8 +6,11 @@ on:
 
 jobs:
   build:
-
     runs-on: self-hosted
+
+    defaults:
+      run:
+        shell: sudo -u github-runner bash -e {0}
 
     strategy:
       matrix:
@@ -15,18 +18,34 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
+
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v4
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
-    - run: |
-        npm install
 
-    - name: create file .env
+    - name: Check user and permissions
       run: |
-        touch .env
-        echo "PORT=${{secrets.PORT}}" > .env
+        echo "=== Current Running User ==="
+        whoami
+
+        echo "=== Current Working Directory ==="
+        pwd
+
+        echo "=== Check Workspace Write Permission ==="
+        if [ -w . ]; then echo "Write access: YES"; else echo "Write access: NO"; fi
+
+        echo "=== Check PM2 Status & Path ==="
+        which pm2 || echo "PM2 is not in PATH"
+        pm2 -v || echo "Failed to run PM2"
+
+
+    - name: Install dependencies
+      run: npm install
+
+    - name: Create .env file
+      run: echo "PORT=${{ secrets.PORT }}" > .env
+
     - name: Restart github CI/CD service
-      shell: bash
-      run: pm2 restart github-cicd || pm2 start server.js --name "github-cicd"
+      run: sudo -u github-runner bash -c "pm2 restart github-cicd || pm2 start server.js --name github-cicd"
